-- ==========================================
-- Orden de creacion de tablas para la base de datos HUELLITAS
-- 1 HUELLITAS_TABLAS.sql
-- 2 HUELLITAS_FUNCIONES.sql
-- 3 HUELLITAS_TRIGGERS.sql
-- 4 HUELLITAS_PROCEDIMIENTOS.sql
-- 5 HUELLITAS_VISTAS.sql
-- 6 HUELLITAS_PRUEBAS.sql
-- ==========================================

use HUELLITASDIGITAL;

INSERT INTO HUELLITAS_ESTADO_TB (ESTADO_DESCRIPCION) VALUES 
('ACTIVO'),
('INACTIVO');

INSERT INTO HUELLITAS_NUEVO_TB (NUEVO_DESCRIPCION) VALUES 
('ES NUEVO'),
('NO ES NUEVO');

INSERT INTO HUELLITAS_SLIDER_BANNER_TB (IMAGEN_URL, DESCRIPCION_SLIDER_BANNER, ID_ESTADO_FK)
VALUES 
('https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/sliderBanner%2F68f0083dce5df_1080x300.png?alt=media',
 'Cuidamos de tus mascotas con amor y experiencia veterinaria.', 1),

('https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/sliderBanner%2F68f0084b8f89e_1080x300%20%281%29.png?alt=media',
 'Promoción del mes: 20% de descuento en alimentos premium para perros y gatos.', 1),

('https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/sliderBanner%2F68f00858e656d_1080x300%20%282%29.png?alt=media',
 'Agenda tu cita para vacunación y chequeos veterinarios en línea.', 1);

INSERT INTO HUELLITAS_PRODUCTOS_CATEGORIA_TB (ID_ESTADO_FK, DESCRIPCION_CATEGORIA) VALUES
(1, 'Medicamentos'),
(1, 'Accesorios'),
(1, 'Alimentos'),
(1, 'Cuidado para Mascota');

-- Inserciones de 10 proveedores mediante el procedimiento almacenado
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('PetSupply CR', 'Laura Hernández', 'contacto@petsupplycr.com', 1, 88871234);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('Alimentos Mascota', 'José Gómez', 'ventas@alimentosmascota.com', 1, 87562345);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('VetPro Distribuciones', 'Andrea Campos', 'info@vetprocr.com', 1, 84123456);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('PetLine Costa Rica', 'Carlos Rodríguez', 'carlos@petlinecr.com', 1, 83987654);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('NaturalPet CR', 'María Solano', 'ventas@naturalpetcr.com', 1, 87091234);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('SuperMascotas S.A.', 'Fernando Jiménez', 'fernando@supermascotas.com', 1, 88882211);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('HappyPets', 'Daniela Vargas', 'contacto@happypetscr.com', 1, 84213465);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('Distribuidora AnimalCare', 'Esteban Mora', 'esteban@animalcarecr.com', 1, 87996543);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('PetZone', 'Melissa Araya', 'melissa@petzonecr.com', 1, 83004567);
CALL HUELLITAS_AGREGAR_PROVEEDOR_SP('Mascotas del Valle', 'Ricardo López', 'ricardo@mascotasvalle.com', 1, 88213456);

-- Inserciones de Productos mediante el procedimiento almacenado

CALL HUELLITAS_AGREGAR_MARCA_SP('ProPlan', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68e8919729a9a_Purina-proplan-logo-transparente.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('NutriSource', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68ed7b37786d6_Captura%20de%20pantalla%202025-10-13%20162027.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Calox Veterinaria', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68ed7b7494362_9-compressor.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Credelio', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68ed7bb286ae4_credelio-lotilaner-logo-png_seeklogo-343513.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Balance', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68ed7bef03bff_Captura%20de%20pantalla%202025-10-13%20162322.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Toons', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68ed7c2a0a4e1_toonslogo.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Virbac', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68ed7c892fa51_Captura%20de%20pantalla%202025-10-13%20162555.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Seresto', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68eec9912ba70_Captura%20de%20pantalla%202025-10-14%20160644.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Pedigree', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68eecbe5cd685_Captura%20de%20pantalla%202025-10-14%20161659.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Purina Cat Chow', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68eecc72d3bdf_images.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Bravecto', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68eeccc166839_Captura%20de%20pantalla%202025-10-14%20162028.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Purina ONE', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68f0076a87740_images%20%281%29.png?alt=media');
CALL HUELLITAS_AGREGAR_MARCA_SP('Hills Science Diet', 1, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2Fmarcas%2F68eed87e00e51_Captura%20de%20pantalla%202025-10-14%20171019.png?alt=media');


CALL HUELLITAS_AGREGAR_PRODUCTO_SP(1, 1, 3, 1, 1, 'ProPlan Adulto Raza Pequeña 1Kg', 'Croquetas premium con proteínas de alta calidad para perros adultos de raza mediana.', 6150, 50, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68edd67ca4eaa_img-proplan-Puppy.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(2, 1, 3, 10, 1, 'Cat Chow Adultos Pollo 1.5Kg', 'Alimento completo y balanceado para gatos adultos sabor pollo.', 6300, 60, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f001b3776a4_Captura%20de%20pantalla%202025-10-15%20141848.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(3, 1, 1, 3, 1, 'Crema Cicatrizante Calox 15g', 'Pomada veterinaria que ayuda en la regeneración y cicatrización de heridas leves en la piel de mascotas.', 2500, 40, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f0053a7da12_Captura%20de%20pantalla%202025-10-15%20143351.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(4, 1, 4, 6, 2, 'Shampoo Toons 265ml', 'Shampoo suave con fragancia agradable que limpia y cuida el pelaje de perros adultos, ideal para uso frecuente.', 1775, 75, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68ede08890f8c_Captura%20de%20pantalla%202025-10-13%20232409.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(5, 1, 1, 4, 1, 'Pastilla Credelio Perros 11-22kg', 'Tableta masticable para control mensual de pulgas y garrapatas.', 14525, 45, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68edead85943a_Captura%20de%20pantalla%202025-10-14%20001332.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(6, 1, 3, 5, 2, 'Balance Adulto Pollo y Arroz 2Kg', 'Alimento seco con proteínas de pollo y cereales integrales para perros adultos.', 3500, 80, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f0007f47052_7443007533202-Basico-Perro-Adulto-Raza-mediana-Pollo-14.97kg.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(7, 1, 4, 6, 1, 'Colonia Toons 125ml', 'Colonia con aroma fresco y duradero que deja el pelaje de tu mascota con un olor agradable después del baño.', 3100, 30, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f00296027ad_Captura%20de%20pantalla%202025-10-15%20142232.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(8, 1, 3, 2, 2, 'NutriSource Raza Pequeña 1.8Kg ', 'Fórmula balanceada para cachorros con DHA y proteínas de pollo.', 10250, 70, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68ede9d81d610_Captura%20de%20pantalla%202025-10-14%20001231.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(9, 1, 1, 7, 1, 'Pastilla Endogard hasta 10Kg', 'Antibiótico de uso veterinario para infecciones respiratorias y cutáneas.', 1750, 35, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68edebac82d75_Endogard10-2600x600%20%281%29.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(10, 1, 4, 8, 1, 'Seresto Collar Antipulgas Grande', 'Collar de larga duración contra pulgas y garrapatas (8 meses de protección).', 35150, 60, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f002ce5ba8f_1-282.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(1, 1, 3, 9, 2, 'Saco Pedigree Adulto Carne y Vegetales 21Kg', 'Alimento seco para perros adultos sabor carne y vegetales.', 31000, 90, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f00399e6515_Captura%20de%20pantalla%202025-10-15%20142654.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(2, 1, 3, 12, 1, 'Purina ONE Gato Esterilizado 2Kg', 'Fórmula especializada para gatos esterilizados que ayuda al control de peso.', 12200, 55, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f00165ce2eb_Captura%20de%20pantalla%202025-10-15%20141719.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(3, 1, 1, 11, 1, 'Bravecto Tableta 20-40kg', 'Antiparasitario oral de acción prolongada (3 meses) para perros grandes.', 32000, 50, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f004e94e2d5_Captura%20de%20pantalla%202025-10-15%20143227.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(4, 1, 4, 6, 2, 'Shampoo para Cachoro Toons', 'Shampoo hipoalergénico para cachorros con fórmula suave que limpia sin irritar la piel ni los ojos.', 4325, 25, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f0047bd89bd_Dise%C3%B1o%20sin%20t%C3%ADtulo%20%282%29.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(5, 1, 3, 13, 1, 'Hills Science Diet Gato Light 1.8Kg', 'Alimento bajo en calorías para control de peso en gatos adultos.', 22030, 40, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f002261cbb2_Captura%20de%20pantalla%202025-10-15%20142046.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(9, 1, 3, 10, 1, 'Cat Chow Gatitos 500g', 'Alimento con DHA para el desarrollo del cerebro y la visión en gatitos.', 5510, 65, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f000fc639ff_Captura%20de%20pantalla%202025-10-15%20141542.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(10, 1, 3, 2, 2, 'NutriSource Senior 1.8Kg', 'Alimento balanceado para perros mayores con ingredientes de fácil digestión.', 9550, 50, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68f0032ece15d_2-4-1.png?alt=media');
CALL HUELLITAS_AGREGAR_PRODUCTO_SP(1, 1, 1, 10, 1, 'Himalaya Digyton Gotas', 'Digestivo: estimula la secreción de las enzimas proteolíticas, amilolíticas y lipolíticas, lo cual cataliza la digestión de los alimentos. Actúa como carminativo, elimina los problemas de flatulencia, cólicos y distención abdominal. Regula la peristalsis (motilidad intestinal), normalizando problemas de estreñimiento y diarreas leves. Mejora el apetito y la asimilación de alimentos en cachorros. Incrementa la tolerancia a cambios repentinos de dieta. Evita los trastornos gastrointestinales en cachorros destetados.', 6150, 50, 'https://firebasestorage.googleapis.com/v0/b/huellitasdigital-443e0.firebasestorage.app/o/productos%2F68e8936b1aba2_img-digyton.png?alt=media');


INSERT INTO HUELLITAS_ROL_USUARIO_TB (ID_ESTADO_FK, DESCRIPCION_ROL_USUARIO) VALUES 
(1, 'CLIENTE'),
(1, 'ADMINISTRADOR'),
(1, 'EMPLEADO'),
(1, 'VETERINARIO');

INSERT INTO HUELLITAS_DIRECCION_PROVINCIA_TB (ID_ESTADO_FK, NOMBRE_PROVINCIA) VALUES 
(1, 'San José'),
(1, 'Alajuela'),
(1, 'Cartago'),
(1, 'Heredia'),
(1, 'Guanacaste'),
(1, 'Puntarenas'),
(1, 'Limón');

-- PROVINCIA 1: San José
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(1, 1, 'San José'),
(1, 1, 'Escazú'),
(1, 1, 'Desamparados'),
(1, 1, 'Puriscal'),
(1, 1, 'Tarrazú'),
(1, 1, 'Aserrí'),
(1, 1, 'Mora'),
(1, 1, 'Goicoechea'),
(1, 1, 'Santa Ana'),
(1, 1, 'Alajuelita'),
(1, 1, 'Vásquez de Coronado'),
(1, 1, 'Acosta'),
(1, 1, 'Tibás'),
(1, 1, 'Moravia'),
(1, 1, 'Montes de Oca'),
(1, 1, 'Turrubares'),
(1, 1, 'Dota'),
(1, 1, 'Curridabat'),
(1, 1, 'Pérez Zeledón'),
(1, 1, 'León Cortéz Castro');

-- PROVINCIA 2: Alajuela
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(2, 1, 'Alajuela'),
(2, 1, 'San Ramón'),
(2, 1, 'Grecia'),
(2, 1, 'San Mateo'),
(2, 1, 'Atenas'),
(2, 1, 'Naranjo'),
(2, 1, 'Palmares'),
(2, 1, 'Poás'),
(2, 1, 'Orotina'),
(2, 1, 'San Carlos'),
(2, 1, 'Zarcero'),
(2, 1, 'Valverde Vega'),
(2, 1, 'Upala'),
(2, 1, 'Los Chiles'),
(2, 1, 'Guatuso');

-- PROVINCIA 3: Cartago
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(3, 1, 'Cartago'),
(3, 1, 'Paraíso'),
(3, 1, 'La Unión'),
(3, 1, 'Jiménez'),
(3, 1, 'Turrialba'),
(3, 1, 'Alvarado'),
(3, 1, 'Oreamuno'),
(3, 1, 'El Guarco');

-- PROVINCIA 4: Heredia
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(4, 1, 'Heredia'),
(4, 1, 'Barva'),
(4, 1, 'Santo Domingo'),
(4, 1, 'Santa Bárbara'),
(4, 1, 'San Rafaél'),
(4, 1, 'San Isidro'),
(4, 1, 'Belén'),
(4, 1, 'Flores'),
(4, 1, 'San Pablo'),
(4, 1, 'Sarapiquí');

-- PROVINCIA 5: Guanacaste
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(5, 1, 'Liberia'),
(5, 1, 'Nicoya'),
(5, 1, 'Santa Cruz'),
(5, 1, 'Bagaces'),
(5, 1, 'Carrillo'),
(5, 1, 'Cañas'),
(5, 1, 'Abangáres'),
(5, 1, 'Tilarán'),
(5, 1, 'Nandayure'),
(5, 1, 'La Cruz'),
(5, 1, 'Hojancha');

-- PROVINCIA 6: Puntarenas
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(6, 1, 'Puntarenas'),
(6, 1, 'Esparza'),
(6, 1, 'Buenos Aires'),
(6, 1, 'Montes de Oro'),
(6, 1, 'Osa'),
(6, 1, 'Aguirre'),
(6, 1, 'Golfito'),
(6, 1, 'Coto Brus'),
(6, 1, 'Parrita'),
(6, 1, 'Corredores'),
(6, 1, 'Garabito');

-- PROVINCIA 7: Limón
INSERT INTO HUELLITAS_DIRECCION_CANTON_TB (ID_PROVINCIA_FK, ID_ESTADO_FK, NOMBRE_CANTON) VALUES
(7, 1, 'Limón'),
(7, 1, 'Pococí'),
(7, 1, 'Siquirres'),
(7, 1, 'Talamanca'),
(7, 1, 'Matina'),
(7, 1, 'Guácimo');


INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'CARMEN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'MERCED');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'HOSPITAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'CATEDRAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'ZAPOTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'SAN FRANCISCO DE DOS RÍOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'URUCA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'MATA REDONDA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'PAVAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'HATILLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '1', '1', 'SAN SEBASTIÁN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '2', '1', 'ESCAZÚ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '2', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '2', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'DESAMPARADOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'SAN MIGUEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'SAN JUAN DE DIOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'SAN RAFAEL ARRIBA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'FRAILES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'PATARRÁ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'SAN CRISTÓBAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'ROSARIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'DAMAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'SAN RAFAEL ABAJO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'GRAVILIAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '3', '1', 'LOS GUIDO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'SANTIAGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'MERCEDES SUR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'BARBACOAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'GRIFO ALTO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'CANDELARITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'DESAMPARADITOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '4', '1', 'CHIRES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '5', '1', 'SAN MARCOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '5', '1', 'SAN LORENZO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '5', '1', 'SAN CARLOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'ASERRI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'TARBACA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'VUELTA DE JORCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'SAN GABRIEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'LEGUA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'MONTERREY');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '6', '1', 'SALITRILLOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'COLÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'GUAYABO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'TABARCIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'PIEDRAS NEGRAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'PICAGRES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'JARIS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '7', '1', 'QUITIRRISI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'GUADALUPE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'SAN FRANCISCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'CALLE BLANCOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'MATA DE PLÁTANO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'IPÍS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'RANCHO REDONDO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '8', '1', 'PURRAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '9', '1', 'SANTA ANA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '9', '1', 'SALITRAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '9', '1', 'POZOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '9', '1', 'URUCA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '9', '1', 'PIEDADES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '9', '1', 'BRASIL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '10', '1', 'ALAJUELITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '10', '1', 'SAN JOSECITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '10', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '10', '1', 'CONCEPCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '10', '1', 'SAN FELIPE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '11', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '11', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '11', '1', 'DULCE NOMBRE DE JESÚS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '11', '1', 'PATALILLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '11', '1', 'CASCAJAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '12', '1', 'SAN IGNACIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '12', '1', 'GUAITIL Villa');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '12', '1', 'PALMICHAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '12', '1', 'CANGREJAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '12', '1', 'SABANILLAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '13', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '13', '1', 'CINCO ESQUINAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '13', '1', 'ANSELMO LLORENTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '13', '1', 'LEON XIII');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '13', '1', 'COLIMA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '14', '1', 'SAN VICENTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '14', '1', 'SAN JERÓNIMO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '14', '1', 'LA TRINIDAD');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '15', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '15', '1', 'SABANILLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '15', '1', 'MERCEDES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '15', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '16', '1', 'SAN PABLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '16', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '16', '1', 'SAN JUAN DE MATA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '16', '1', 'SAN LUIS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '16', '1', 'CARARA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '17', '1', 'SANTA MARÍA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '17', '1', 'JARDÍN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '17', '1', 'COPEY');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '18', '1', 'CURRIDABAT');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '18', '1', 'GRANADILLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '18', '1', 'SÁNCHEZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '18', '1', 'TIRRASES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'SAN ISIDRO DE EL GENERAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'EL GENERAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'DANIEL FLORES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'RIVAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'PLATANARES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'PEJIBAYE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'CAJÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'BARÚ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'RÍO NUEVO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '19', '1', 'PÁRAMO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '20', '1', 'SAN PABLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '20', '1', 'SAN ANDRÉS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '20', '1', 'LLANO BONITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '20', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '20', '1', 'SANTA CRUZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '20', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'ALAJUELA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'SAN JOSÉ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'CARRIZAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'GUÁCIMA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'SABANILLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'RÍO SEGUNDO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'DESAMPARADOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'TURRÚCARES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'TAMBOR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'GARITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '21', '1', 'SARAPIQUÍ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'SAN RAMÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'SANTIAGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'PIEDADES NORTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'PIEDADES SUR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'ÁNGELES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'ALFARO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'VOLIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'CONCEPCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'ZAPOTAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '22', '1', 'PEÑAS BLANCAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'GRECIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'SAN JOSÉ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'SAN ROQUE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'TACARES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'RÍO CUARTO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'PUENTE DE PIEDRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '23', '1', 'BOLÍVAR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '24', '1', 'SAN MATEO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '24', '1', 'DESMONTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '24', '1', 'JESÚS MARÍA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '24', '1', 'LABRADOR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'ATENAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'JESÚS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'MERCEDES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'CONCEPCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'SAN JOSE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'SANTA EULALIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '25', '1', 'ESCOBAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'NARANJO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'SAN MIGUEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'SAN JOSÉ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'CIRRÍ SUR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'SAN JERÓNIMO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'EL ROSARIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '26', '1', 'PALMITOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'PALMARES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'ZARAGOZA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'BUENOS AIRES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'SANTIAGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'CANDELARIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'ESQUÍPULAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '27', '1', 'LA GRANJA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '28', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '28', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '28', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '28', '1', 'CARRILLOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '28', '1', 'SABANA REDONDA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '29', '1', 'OROTINA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '29', '1', 'EL MASTATE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '29', '1', 'HACIENDA VIEJA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '29', '1', 'COYOLAR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '29', '1', 'LA CEIBA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'QUESADA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'FLORENCIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'BUENAVISTA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'AGUAS ZARCAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'VENECIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'PITAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'LA FORTUNA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'LA TIGRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'LA PALMERA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'VENADO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'CUTRIS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'MONTERREY');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '30', '1', 'POCOSOL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '31', '1', 'ZARCERO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '31', '1', 'LAGUNA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '31', '1', 'GUADALUPE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '31', '1', 'PALMIRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '31', '1', 'ZAPOTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '31', '1', 'BRISAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '32', '1', 'SARCHÍ NORTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '32', '1', 'SARCHÍ SUR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '32', '1', 'TORO AMARILLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '32', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '32', '1', 'RODRÍGUEZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'UPALA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'AGUAS CLARAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'SAN JOSÉ o PIZOTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'BIJAGUA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'DELICIAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'DOS RÍOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'YOLILLAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '33', '1', 'CANALETE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '34', '1', 'LOS CHILES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '34', '1', 'CAÑO NEGRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '34', '1', 'EL AMPARO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '34', '1', 'SAN JORGE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '35', '1', 'BUENAVISTA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '35', '1', 'COTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '35', '1', 'KATIRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'ORIENTAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'OCCIDENTAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'CARMEN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'SAN NICOLÁS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'AGUACALIENTE o SAN FRANCISCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'GUADALUPE o ARENILLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'CORRALILLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'TIERRA BLANCA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'DULCE NOMBRE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'LLANO GRANDE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '36', '1', 'QUEBRADILLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '37', '1', 'PARAÍSO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '37', '1', 'SANTIAGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '37', '1', 'OROSI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '37', '1', 'CACHÍ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '37', '1', 'LLANOS DE SANTA LUCÍA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'TRES RÍOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'SAN DIEGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'CONCEPCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'DULCE NOMBRE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'SAN RAMÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '38', '1', 'RÍO AZUL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '39', '1', 'JUAN VIÑAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '39', '1', 'TUCURRIQUE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '39', '1', 'PEJIBAYE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'TURRIALBA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'LA SUIZA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'PERALTA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'SANTA CRUZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'SANTA TERESITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'PAVONES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'TUIS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'TAYUTIC');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'SANTA ROSA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'TRES EQUIS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'LA ISABEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '40', '1', 'CHIRRIPÓ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '41', '1', 'PACAYAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '41', '1', 'CERVANTES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '41', '1', 'CAPELLADES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '42', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '42', '1', 'COT');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '42', '1', 'POTRERO CERRADO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '42', '1', 'CIPRESES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '42', '1', 'SANTA ROSA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '43', '1', 'EL TEJAR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '43', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '43', '1', 'TOBOSI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '43', '1', 'PATIO DE AGUA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '44', '1', 'HEREDIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '44', '1', 'MERCEDES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '44', '1', 'SAN FRANCISCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '44', '1', 'ULLOA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '44', '1', 'VARABLANCA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '45', '1', 'BARVA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '45', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '45', '1', 'SAN PABLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '45', '1', 'SAN ROQUE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '45', '1', 'SANTA LUCÍA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '45', '1', 'SAN JOSÉ DE LA MONTAÑA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'SAN VICENTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'SAN MIGUEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'PARACITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'SANTO TOMÁS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'SANTA ROSA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'TURES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '46', '1', 'PARÁ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '47', '1', 'SANTA BÁRBARA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '47', '1', 'SAN PEDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '47', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '47', '1', 'JESÚS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '47', '1', 'SANTO DOMINGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '47', '1', 'PURABÁ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '48', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '48', '1', 'SAN JOSECITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '48', '1', 'SANTIAGO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '48', '1', 'ÁNGELES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '48', '1', 'CONCEPCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '49', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '49', '1', 'SAN JOSÉ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '49', '1', 'CONCEPCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '49', '1', 'SAN FRANCISCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '50', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '50', '1', 'LA RIBERA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '50', '1', 'LA ASUNCIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '51', '1', 'SAN JOAQUÍN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '51', '1', 'BARRANTES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '51', '1', 'LLORENTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '52', '1', 'SAN PABLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '53', '1', 'PUERTO VIEJO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '53', '1', 'LA VIRGEN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '53', '1', 'LAS HORQUETAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '53', '1', 'LLANURAS DEL GASPAR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '53', '1', 'CUREÑA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '54', '1', 'LIBERIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '54', '1', 'CAÑAS DULCES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '54', '1', 'MAYORGA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '54', '1', 'NACASCOLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '54', '1', 'CURUBANDÉ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'NICOYA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'MANSIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'SAN ANTONIO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'QUEBRADA HONDA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'SÁMARA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'NOSARA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '55', '1', 'BELÉN DE NOSARITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'SANTA CRUZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'BOLSÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'VEINTISIETE DE ABRIL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'TEMPATE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'CARTAGENA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'CUAJINIQUIL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'DIRIÁ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'CABO VELAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '56', '1', 'TAMARINDO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '57', '1', 'BAGACES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '57', '1', 'LA FORTUNA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '57', '1', 'MOGOTE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '57', '1', 'RÍO NARANJO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '58', '1', 'FILADELFIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '58', '1', 'PALMIRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '58', '1', 'SARDINAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '58', '1', 'BELÉN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '59', '1', 'CAÑAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '59', '1', 'PALMIRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '59', '1', 'SAN MIGUEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '59', '1', 'BEBEDERO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '59', '1', 'POROZAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '60', '1', 'LAS JUNTAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '60', '1', 'SIERRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '60', '1', 'SAN JUAN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '60', '1', 'COLORADO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'TILARÁN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'QUEBRADA GRANDE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'TRONADORA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'SANTA ROSA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'LÍBANO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'TIERRAS MORENAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '61', '1', 'ARENAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '62', '1', 'CARMONA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '62', '1', 'SANTA RITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '62', '1', 'ZAPOTAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '62', '1', 'SAN PABLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '62', '1', 'PORVENIR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '62', '1', 'BEJUCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '63', '1', 'LA CRUZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '63', '1', 'SANTA CECILIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '63', '1', 'LA GARITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '63', '1', 'SANTA ELENA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '64', '1', 'HOJANCHA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '64', '1', 'MONTE ROMO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '64', '1', 'PUERTO CARRILLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '64', '1', 'HUACAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'PUNTARENAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'PITAHAYA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'CHOMES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'LEPANTO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'PAQUERA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'MANZANILLO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'GUACIMAL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'BARRANCA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'MONTE VERDE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'CÓBANO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'CHACARITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'CHIRA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'ACAPULCO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'EL ROBLE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '65', '1', 'ARANCIBIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '66', '1', 'ESPÍRITU SANTO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '66', '1', 'SAN JUAN GRANDE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '66', '1', 'MACACONA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '66', '1', 'SAN RAFAEL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '66', '1', 'SAN JERÓNIMO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '66', '1', 'CALDERA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'BUENOS AIRES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'VOLCÁN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'POTRERO GRANDE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'BORUCA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'PILAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'COLINAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'CHÁNGUENA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'BIOLLEY');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '67', '1', 'BRUNKA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '68', '1', 'MIRAMAR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '68', '1', 'LA UNIÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '68', '1', 'SAN ISIDRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '69', '1', 'PUERTO CORTÉS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '69', '1', 'PALMAR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '69', '1', 'SIERPE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '69', '1', 'BAHÍA BALLENA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '69', '1', 'PIEDRAS BLANCAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '69', '1', 'BAHÍA DRAKE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '70', '1', 'QUEPOS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '70', '1', 'SAVEGRE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '70', '1', 'NARANJITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '71', '1', 'GOLFITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '71', '1', 'PUERTO JIMÉNEZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '71', '1', 'GUAYCARÁ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '71', '1', 'PAVÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '72', '1', 'SAN VITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '72', '1', 'SABALITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '72', '1', 'AGUABUENA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '72', '1', 'LIMONCITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '72', '1', 'PITTIER');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '72', '1', 'GUTIERREZ BRAUN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '73', '1', 'PARRITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '74', '1', 'CORREDOR');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '74', '1', 'LA CUESTA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '74', '1', 'CANOAS');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '74', '1', 'LAUREL');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '75', '1', 'JACÓ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '75', '1', 'TÁRCOLES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '76', '1', 'LIMÓN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '76', '1', 'VALLE LA ESTRELLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '76', '1', 'MATAMA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'GUÁPILES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'JIMÉNEZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'RITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'ROXANA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'CARIARI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'COLORADO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '77', '1', 'LA COLONIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '78', '1', 'SIQUIRRES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '78', '1', 'PACUARITO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '78', '1', 'FLORIDA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '78', '1', 'GERMANIA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '78', '1', 'EL CAIRO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '78', '1', 'ALEGRÍA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '79', '1', 'BRATSI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '79', '1', 'SIXAOLA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '79', '1', 'CAHUITA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '79', '1', 'TELIRE');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '80', '1', 'MATINA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '80', '1', 'BATÁN');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '80', '1', 'CARRANDI');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '81', '1', 'GUÁCIMO');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '81', '1', 'MERCEDES');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '81', '1', 'POCORA');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '81', '1', 'RÍO JIMÉNEZ');
INSERT INTO HUELLITAS_DIRECCION_DISTRITO_TB (ID_CANTON_FK, ID_ESTADO_FK, NOMBRE_DISTRITO) VALUES ( '81', '1', 'DUACARÍ');


INSERT INTO HUELLITAS_DIRECCION_TB (ID_ESTADO_FK, ID_DIRECCION_PROVINCIA_FK, ID_DIRECCION_CANTON_FK, ID_DIRECCION_DISTRITO_FK, DIRECCION_SENNAS) VALUES 
(1, 1, 1, 1, 'AVENIDA CENTRAL, CALLE 25, CASA 456');

INSERT INTO HUELLITAS_TELEFONO_CONTACTO_TB (ID_ESTADO_FK, TELEFONO_CONTACTO) VALUES 
(1, 88889999);


-- Crear claves de encriptación
INSERT INTO HUELLITAS_CLAVES_ENCRIPTACION_TB (NOMBRE_CLAVE, CLAVE_ENCRIPTACION) VALUES 
('CLAVE_NUMERO_TARJETA', HUELLITAS_GENERAR_CLAVE_AES_FN()),
('CLAVE_CVV', HUELLITAS_GENERAR_CLAVE_AES_FN()),
('CLAVE_CONTRASENNA', HUELLITAS_GENERAR_CLAVE_AES_FN());


INSERT INTO HUELLITAS_USUARIOS_TB (
    ID_ESTADO_FK, 
    ID_ROL_USUARIO_FK, 
    ID_DIRECCION_FK, 
    ID_TELEFONO_CONTACTO_FK,
    USUARIO_NOMBRE, 
    USUARIO_CORREO, 
    USUARIO_CONTRASENNA,
    USUARIO_IDENTIFICACION
) VALUES (
    1,  -- ACTIVO
    1,  -- CLIENTE
    1,  -- DIRECCIÓN
    1,  -- TELÉFONO
    'MARÍA FERNANDA LÓPEZ GARCÍA',
    'maria.lopez@email.com',
    'ClaveSegura2024!',
    123456789
);

-- Usuario Admin
INSERT INTO HUELLITAS_USUARIOS_TB (
    ID_ESTADO_FK, 
    ID_ROL_USUARIO_FK, 
    ID_DIRECCION_FK, 
    ID_TELEFONO_CONTACTO_FK,
    USUARIO_NOMBRE, 
    USUARIO_CORREO, 
    USUARIO_CONTRASENNA,
    USUARIO_IDENTIFICACION
) VALUES (
    1,  -- ACTIVO
    2,  -- ADMINITRADOR
    1,  -- DIRECCIÓN
    1,  -- TELÉFONO
    'José Admin Rojas Gonzales',
    'jose.gonzales@email.com',
    'ClaveSegura2024!',
    987654321
);

INSERT INTO HUELLITAS_TARJETAS_TB (
    ID_USUARIO_FK,
    TIPO_TARJETA,
    MARCA_TARJETA,
    NOMBRE_TITULAR,
    NUMERO_TARJETA_ENCRIPTADO,
    ULTIMOS_CUATRO_DIGITOS,
    FECHA_VENCIMIENTO,
    CVV_ENCRIPTADO,
    ES_PREDETERMINADO,
    IP_REGISTRO
) VALUES (
    1,  -- ID del usuario recién insertado
    'CREDITO',
    'VISA',
    'MARIA FERNANDA LOPEZ',
    '4111111111111111',  -- Se encriptará automáticamente
    '1111',
    '2027-05-20',
    '123',               -- Se encriptará automáticamente
    TRUE,
    '192.168.1.100'
);


INSERT INTO HUELLITAS_PRODUCTOS_COMENTARIOS_TB 
(ID_PRODUCTO_FK, ID_USUARIO_FK, ID_ESTADO_FK, COMENTARIO_TEXTO, CALIFICACION_TIPO)
VALUES
(1, 1, 1, 'Excelente calidad, mi mascota lo ama.', '5'),
(2, 2, 1, 'Llegó rápido y bien empacado.', '4'),
(3, 1, 1, 'No le gustó mucho el sabor, pero el servicio fue bueno.', '3'),
(4, 2, 1, 'Producto muy útil, justo lo que necesitaba.', '5'),
(5, 1, 2, 'El empaque vino dañado.', '2'),
(6, 2, 1, 'Mi perro está feliz con este juguete.', '5'),
(7, 1, 1, 'Calidad aceptable por el precio.', '3'),
(8, 2, 1, 'El envío fue más rápido de lo esperado.', '4'),
(9, 1, 2, 'El tamaño no coincidía con la descripción.', '2'),
(10, 2, 1, 'Excelente producto, muy recomendado.', '5'),
(11, 1, 1, 'Mi gato se adaptó muy bien a este alimento.', '4'),
(12, 2, 1, 'Cumple su función, nada extraordinario.', '3'),
(13, 1, 1, 'Buena relación calidad-precio.', '4'),
(14, 2, 2, 'No funcionó como esperaba.', '1'),
(15, 1, 1, 'Totalmente satisfecho con la compra.', '5'),
(3, 2, 1, 'Buen sabor según mi perro, volveré a comprar.', '4'),
(5, 1, 1, 'La textura es perfecta para mi mascota senior.', '5'),
(8, 2, 2, 'El producto venía incompleto.', '1'),
(10, 1, 1, 'Muy buen servicio al cliente, resolvieron mis dudas.', '4'),
(12, 2, 1, 'Producto fresco y en excelente estado.', '5');



-------------------------------------------------------------------------------------------------
-------------------------------------- Pruebas Encriptacion --------------------------------------------
-------------------------------------------------------------------------------------------------

-- Verificar usuario
SELECT 
    ID_USUARIO_PK,
    USUARIO_NOMBRE,
    USUARIO_CONTRASENNA,
    USUARIO_CONTRASENNA_ENCRIPTADA,
    USUARIO_SALT
FROM HUELLITAS_USUARIOS_TB;

-- Verificar tarjeta
SELECT 
    ID_TARJETA_PK,
    NUMERO_TARJETA_ENCRIPTADO,
    ULTIMOS_CUATRO_DIGITOS,
    CVV_ENCRIPTADO,
    LENGTH(NUMERO_TARJETA_ENCRIPTADO) AS LONG_NUMERO,
    LENGTH(CVV_ENCRIPTADO) AS LONG_CVV
FROM HUELLITAS_TARJETAS_TB;

-- Probar desencriptación de tarjeta
SELECT
    ID_TARJETA_PK,
    NOMBRE_TITULAR,
    ULTIMOS_CUATRO_DIGITOS,
    HUELLITAS_DESENCRIPTAR_DATO_FN(NUMERO_TARJETA_ENCRIPTADO, 'CLAVE_NUMERO_TARJETA') AS NUMERO_DESENCRIPTADO,
    HUELLITAS_DESENCRIPTAR_DATO_FN(CVV_ENCRIPTADO, 'CLAVE_CVV') AS CVV_DESENCRIPTADO
FROM HUELLITAS_TARJETAS_TB;

-------------------------------------------------------------------------------------------------
-------------------------------------- Pruebas login --------------------------------------------
-------------------------------------------------------------------------------------------------
-- Probar login exitoso
CALL HUELLITAS_VALIDAR_LOGIN_SP('maria.lopez@email.com', 'ClaveSegura2024!');

-- Probar login fallido
CALL HUELLITAS_VALIDAR_LOGIN_SP('maria.lopez@email.com', 'clave_incorrecta');

-- Cambiar contraseña
CALL HUELLITAS_CAMBIAR_CONTRASENNA_SP(1, 'ClaveSegura2024!', 'NuevaClaveSuperSegura2024!');

-- Probar que la nueva contraseña funciona
CALL HUELLITAS_VALIDAR_LOGIN_SP('maria.lopez@email.com', 'NuevaClaveSuperSegura2024!');


CALL HUELLITAS_LISTAR_PRODUCTOS_ACTIVOS_SP();